### ISSUE TITLE
Support DB username and password in GKE 

### ISSUE THREAD

**Issue by kevensen** [forseti-security/helm-charts#43]
As a user of Forseti on-GKE, I would like to be able to access the SQL DB with a user name and password in order to assert authentication to the database.

- [ ] https://github.com/forseti-security/forseti-security/issues/3321
- [ ] Add sql_db_password  to server container args or ENV variable
- [ ] Add sql_db_user to server container args or ENV variable

**Comment by kevensen** [comment]
Step 1 - Create a K8s secrets template (e.g. database-secret.yaml) in _charts/forseti-security/templates/server/_ that resembels
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: {{ .Values.database.username }}
  password: {{ .Values.database.password }}
```

Step 2 - Use the [secrets as environment variables](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables)
